### ISSUE TITLE
Don't start CICD pipeline for tags

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/DubUrl#630]
As we're now automatically tagging the commits with a release tag, we should be careful to not restart the pipeline on the tag.

```yml
branches:
  except:
    - /v\d+\.\d+\.\d+/
```
